---
- name: Passwordless Authentication
  hosts: appserv
  remote_user: ansadmin
  become: true
  vars:
        usr: ashok
  tasks:
    - name: Generating public and private keys for user {{usr}}
      user:
        name: '{{usr}}'
        generate_ssh_key: yes
        ssh_key_type: rsa
        state: present

- name: Copy public key to clients
  hosts: appserv, dbserv, webserv
  remote_user: ansadmin
  become: true
  vars:
        usr: ashok
        source: /home/ashok/.ssh/id_rsa.pub
  tasks:
    - name: Fetch public key from mani-ans-serv
      fetch:
        src: '{{source}}'
        dest: /tmp/id_rsa.pub
        flat: yes

    - name: Ensure .ssh directory exists
      file:
        path: ~/.ssh
        state: directory
        mode: '0700'

    - name: Append public key to authorized_keys
      authorized_key:
        user: '{{usr}}'
        key: "{{ lookup('file', '/tmp/id_rsa.pub') }}"
        state: present