---
- name: user creation
  hosts: appserv, dbserv, webserv
  remote_user: ansadmin
  become: true
  vars:
      usr: ashok
      grp: ashok
      grp_id: 5200
      usr_id: 5300
      cmt: ashok@outlook.com
      pwd: ashok@123
  tasks:
        -  name: create a group
           group:
                 name: '{{grp}}'
                 gid: '{{grp_id}}'
        -  name: create a user
           user:
                name: '{{usr}}'
                uid: '{{usr_id}}'
                group: '{{grp_id}}'
                comment: '{{cmt}}'
                password: "{{ '{{pwd}}' | password_hash('sha512') }}"
                state: present