---
- name: change permissions and ownership, group membership of a directory
  hosts: appserv
  remote_user: ansadmin
  become: true
  tasks: 
        -  name: changing /ansible-playbook permissions
           file:
                path: /ansible-playbook
                mode: '0755'
        -  name: changing /ansible-playbook/* files ownership and group membership
           shell: chown root:root /ansible-playbook/*