---
- name: Repo configuration in rhel7.4 reverse
  hosts: appserv, dbserv, webserv
  remote_user: ansadmin
  become: true
  tasks:
        -  name: removing repo file
           file:
                path: /etc/yum.repos.d/rhel74.repo
                state: absent
        -  name: removing rhel7.4 directory
           file:
                path: /var/ftp/pub/rhel7.4
                state: absent