---
- name: Example of Varibles
  hosts: localhost
  gather_facts: no 
  vars_files:
        - /tmp/vars2.yml

  tasks:
      -  name: show variable values
         debug:
            msg: "port is {{http_port}}, username is {{user}}, path is {{path}}"
