---
# tasks file for git_push_playbooks
- name: git inialize in {{destination_path}}
  shell: cd {{destination_path}}; git init
- name: git config
  shell: cd {{destination_path}}; git config {{item.name}} {{item.value}}
  with_items: '{{git_params}}'
- name: git remote add
  shell: cd {{destination_path}}; git remote add origin {{repo_path}}
- name: git pull
  git:
      repo: '{{repo_path}}'
      dest: '{{destination_path}}'
      update: yes
      version: main
- name: copying the directory
  copy:
       src: '{{source_path}}'
       dest: '{{destination_path}}'
       remote_src: yes
- name: git add in {{destination_path}}
  shell: cd {{destination_path}}; git add -A
- name: git commit in {{destination_path}}
  become: yes
  shell: cd {{destination_path}}; git commit -m "added modifications to repository through ansible"
- name: git push
  become: yes
  shell: cd {{destination_path}}; git push origin main
